default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5

development: &development
  <<: *default
  host: localhost
  database: airplane_development
  username: root
  password:

test:
  <<: *development
  database: airplane_test

production:
  <<: *development
  database: airplane_production
