# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3357bc7c31fffc0c49f57cd5f9622079e86f351e963407a00791f100c087b342bba96322a3eb0aba472079a2be86d89b70640eb6939e0ff8eeabb4849c35199f

test:
  secret_key_base: f20d35dc689d6db960f109025efec9762354b2220d3a0dedab2c06a08b3b3cd17e574170a2089b1a9a0ecb3ab12792bbaf7e996da8c4cc69c6d7f25efdcb0330

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
